### ISSUE TITLE
The clear function has breaking changes. Need a new clear function and keep the original unchanged

### ISSUE THREAD

**Issue by oddvarlia** [equinor/libres#1143]
A commit from 25.03.21 changes the behavior of the clear function ( local_config.clear()) in order to be able to setup a localisation where selected correlations are deactivated starting from a full set of possible correlations. This change in the clear() function may have unwanted effect on existing scripts. What can happen with the new version of the clear() function is that re-running a script using clear() at the top of the script and some addNode() calls later in the script will per today create an error since the addNode() function will try to add the same node name again instead of overwriting it with the new one.

Solution1 Make a new clear function (e.g clear_local()) that has the modified clear functionality and reset the original clear function to its original functionality. In localisation setup we need the new clear functionality so reverting the commit is not a solution.

Solution2: Accept that it is possible update a model parameter node or observation node by adding  a node with an existing name and let it overwrite the existing node. In this case just keep the clear function as it is per today and not go back to the old version of the clear() functions functionality.  This solution avoid having to extend the API with a new function and should be a preferred solution.

**Comment by lars-petter-hauge** [comment]
Solution2: I think modifying the behaviour of a different function in order to mitigate changes to the first function is the wrong way to go. Generally I would expect that an `add` function would fail if it tries to add something that already exists. If such a function should have this behaviour I would think it would require an `overwrite=True` or something similar. Furthermore we would still be changing the behaviour and _someone_ might have a setup where they `try` to add a node, and accept that it fails/do something else if it fails.

Solution1: I think resetting the original `clear` function would be the most appropriate. Either make a new clear function which covers the need, or possibly add a keyword argument for a soft clear to the original function (where default is previous behaviour)

**Comment by joakim-hove** [comment]
>Generally I would expect that an add function would fail if it tries to add something that already exists

I guess that is in the mind og the beholder; but this is a "map-like-structure" - and then I think overwriting is a viable alternative. That will also make the whole thing idempotent - which is a Good Thing&trade;

**Comment by markusdregi** [comment]
This had unexpected consequences in existing workflows. We'll start by avoiding the breaking change by extending the API and then afterwards consider how to move forward 👍🏻

**Comment by joakim-hove** [comment]
> We'll start by avoiding the breaking change by extending the API and then afterwards consider how to move forward 👍🏻

OK - I'll make a PR accordingly.

**Comment by markusdregi** [comment]
@joakim-hove: I think @lars-petter-hauge and @oddvarlia is already on it 👍🏻

**Comment by joakim-hove** [comment]
Ahhh ok sorry - my take on it is here: https://github.com/equinor/libres/pull/1147

**Comment by markusdregi** [comment]
Nothing to appologize for! Thanks for the responsiveness 👏🏻

**Comment by lars-petter-hauge** [comment]
I don't mind going ahead with the implementation suggested by @joakim-hove, I spent my time trying to write tests for checking if `clear` behaved as it should (with and without a soft delete) - without really getting anything valuable out of it.

Don't have the same speed I suppose :P

**Comment by markusdregi** [comment]
Resolved in https://github.com/equinor/libres/pull/1147
