### ISSUE TITLE
Difference between <GEO_ID>, %d and <IENS>

### ISSUE THREAD

**Issue by nairr** [equinor/libres#338]
I am creating an ert config file for carrying out an ensemble experiment and am a bit confused between the terms <GEO_ID>, %d and IENS. I would appreciate it if you could help me understand the difference between these terms and what to use when:

1. Using the DEFINE Keyword
2. With ECLBASE
3. Within JOBS, e.g. COPY_FILE
4. Inside the Eclipse DATA file (e.g.  INCLUDE  ../real-<GEO_ID>/include)

**Comment by joakim-hove** [comment]
IENS

**Comment by markusdregi** [comment]
Hi @nairr. Did you figure this out?

**Comment by nairr** [comment]
Hi @markusdregi - not entirely, would appreciate a short explanation or a link to relevant documentation

**Comment by markusdregi** [comment]
When _libres_ is to execute the forward model on a realisation, this execution is given an unique ID/index named called `IENS`. In addition, this simulation is tied to a _geological_ realisation, and the ID of this geological realisation is called `GEO_ID`.

Both of these keywords are substituted at runtime when the forward model is to be executed and they are then substituted with the correct values. So if you are running the realisation with ensemble index `7` and it is simulating the geological realisation with ID `4`, `IENS` will take the value 7 and `GEO_ID` will be `4`.

So if you need to reference these values in other keywords, job arguments or even inside an _Eclipse_ DATA-file, you can use the keyword and it will be replaced when executing the forward model and these keywords take specific values.

One application of this is to structure the runpath (where the execution of all the forward models are happening). However, `<IENS>` is not substituted in the runpath, but you can instead access this value by using `%d`. Hence, if your runpath was `/my/path/<GEO_ID>/%d` in the example above, this would be resolved to `/my/path/4/7`. This `%d` syntax is however specifically for the runpath, and for substitution in the rest of your config file you would use the keywords above..

I hope this was somewhat helpful. If not, please let me know!

**Comment by nairr** [comment]
Thanks @markusdregi. That was very helpful! 

I raised this question since in an earlier version of libres (or ert), I was able to set the GEO_ID inside the eclipse data file (e.g. INCLUDE ../real-<GEO_ID>/include), but after updating to version 2.2, this is somehow not read anymore. This becomes annoying when you use SEBA (or WPRO) for optimization and have multiple perturbations, thus just wondering if there was a workaround to using GEO_ID.

**Comment by markusdregi** [comment]
Yes, there were some issues related to _GEO_ID_  in _2.2_. We resolved it, but I see now that this was not backported to _2.2_. An immediate fix is to use _2.3_ instead, but this is not a stable release yet. Another immediate fix is to change your setup so that it creates a symlink to the `DATA`-file in your runpath, and then copy your _GEO_ID_ specific files into your runpath so that you pick up the right files to include. More specifically; change the include statement in the `DATA`-file to `INCLUDE ../include`, symlink the `DATA`-file into your runpath, copy `real-<GEO_ID>/include` into your runpath to the correct location according to the `.DATA`-file.

But, your original approach should work and will work in the future.
