### ISSUE TITLE
More active use of flow 

### ISSUE THREAD

**Issue by joakim-hove** [equinor/libres#471]
#### Use flow
Testing of the intended use of libres, typically with a forward model including reservoir simulation is not trivial because the test environment typically does not have Eclipse installed; to a lesser extent this also applies to developers who do maybe do not have access to Eclipse - or at least must configure it correctly locally. The opm/flow reservoir simulator has matured significantly, and is in my opinion well suited to be used in test and development of libres - in particular there are [binary packages](https://opm-project.org/?page_id=36) which can be used in a CI setup.

If there is a wish to utilize `flow` more actively in libres testing and development I see the following sub tasks:

##### 1. Configure `ecl_config.yml` by poking in the system

The intended task here is to let `cmake` find the `flow` executable and configure the `ecl_config.yml`file correspondingly if it is found. An initial PR for this is: #472

##### 2. Default version

For Eclipse people generally have quite strong feelings about *versions*; i.e. quite often they specifically run exactly version 2017.1 or 2015.2. With that background it makes sense that Eclipse version has a quite *in-your-face* behavior in the user "api", however for `flow` - at least for the simple test and development addressed here - I assume  exact `flow` version will be of less relevance. I therefor suggest some changes/additions in the handling of versions:

1. Add a alias capability to  `ecl_config.py / ecl_config.yml` - so that version `alias` in the example below can be used as an alternative to the `2018.10` version:
```yml
simulators:
  ecl100:
    '2018.10':  
      scalar:
        executable: /path/ecl/2015.2/linux/x86_64/bin/eclipse100
      mpi:
        executable: /path/ecl/2015.2/linux/x86_64/bin/eclipse100_mpi
        ....

    alias: '2018.10'
```
2. Give semantic meaning to e.g. the version string `default` - so that if no version was explicitly requested the `default` version would be used.

3. The code to actually run the eclipse/flow forward model should shuffle the arguments a bit, so that it can be invoked without an explicit version.

**Comment by markusdregi** [comment]
> If there is a wish to utilize flow more actively in libres testing and development I see the following sub tasks.

I think this is a very good initiative!

**Comment by markusdregi** [comment]
For the default versions, should we consider making it three different config files before we continue? One each for `ecl100`, `ecl300` and `flow`?

Also I find a full scale `alias` mechanism a bit overkill, would not a single `default_version` key do the trick?

**Comment by joakim-hove** [comment]
> For the default versions, should we consider making it three different config files before we continue? One each for ecl100, ecl300 and flow?

That is certainly possible - I guess splitting in three files would increase the admin overhead? But mind you - my thought about a `default` version would be on a *per simulator basis* - not a global default.

> [... ] would not a single default_version key do the trick?

Sure - the important feature is a system for a default version, the alias was really just my suggestion for how it could be implemented.

**Comment by markusdregi** [comment]
> That is certainly possible - I guess splitting in three files would increase the admin overhead? But mind you - my thought about a default version would be on a per simulator basis - not a global default.

Perhaps, I just thought that since they are different executables it would be more natural for users to configure them independently? If you just want `OPM` you have an `OPM` configuration and then if you later want to add `Eclipse` support you do not edit the `OPM` configuration, but create an `Eclipse` configuration...

Really cool that you initiated this. Are you planning to carry out further work in this direction anytime soon?

I would prefer three separate configuration files and then section them along the lines of:
```yaml
default_version: 2018.10

ecl100_versions:
  '2018.10':  
    scalar:
      executable: /path/ecl/2015.2/linux/x86_64/bin/eclipse100
    mpi:
      executable: /path/ecl/2015.2/linux/x86_64/bin/eclipse100_mpi
      ....
```

My current thought regarding _Eclipse_ versions is that for the _simulation jobs_ we make it a command line argument as we have for _RMS_. So that if you want `2018.10` you would do something along the lines of:
`ecl100 --version 2018.10 < the rest of the arguments >` and then surely
`ecl100  < the rest of the arguments >` or (_flow_ for that matter) would default to the value configured. 

Were you also thinking to bring the default value into the _FORWARD MODEL_ jobs? As in `FORWARD_MODEL ECL100(< the rest of the arguments >)` would pick up the default version?

We will probably not push this any further for the next weeks, but if you would like to continue this I'm happy to find a good solution. If not, we'll build on top of this in the not so distant future.

**Comment by joakim-hove** [comment]
> I just thought that since they are different executables it would be more natural for users to configure them independently? 

I agree with your point, however my two minor reasons to hesitate to fully support your view are:

1. Currently the `EclConfig`class very much wraps the `ecl_config.yml` configuration file - if the `ecl_config.yml` file is split in three it would be natural to split this file/implementation as well. All in all that might be a better solution in the end - but fitting three config files into the current `EclConfig`class become slightly weird in my opinions.

2. ERT/libres is not there yet - and maybe will never be, but in my head the `ecl_config.yml` should be configured & edited by operations personell and not developers or users, and then I guess it would be most convenient to have it all in one file.

But anyway - when I am confident we have the same understanding; I will follow your directions.

> Are you planning to carry out further work in this direction anytime soon?

Yes; but don't hold your breath.

I would prefer three separate configuration files and then section them along the lines of:
```
default_version: 2018.10

ecl100_versions:
  '2018.10':  
    scalar:
      executable: /path/ecl/2015.2/linux/x86_64/bin/eclipse100
    mpi:
      executable: /path/ecl/2015.2/linux/x86_64/bin/eclipse100_mpi
      ....
```

I will split if if that is desired, but if all of this a configuration file for Eclipse100 it maybe does not make totally sense to have the `ecl100_versions` top level node?

> [....] . So that if you want 2018.10 you would do something along the lines of:
ecl100 --version 2018.10 < the rest of the arguments > and then surely
ecl100 < the rest of the arguments > or (flow for that matter) would default to the value configured.

Yes.

> Were you also thinking to bring the default value into the FORWARD MODEL jobs? As in FORWARD_MODEL ECL100(< the rest of the arguments >) would pick up the default version?

Yes.

But - I guess it is when come all the way to the `FORWARD_MODEL`compatibility is most challenging.

**Comment by markusdregi** [comment]
> then I guess it would be most convenient to have it all in one file.

I guess this is a personal preference, I would prefer separate configuration files for each job also as a operations personnel also. I would however prefer to have them co-located, but that we can think about and approach later down on.

In general I find the configuration files we now have for ecl and rms to be a great approach that we hopefully can apply to other jobs that needs configuration as well.

> Yes; but don't hold your breath.

I wont ;)

> but if all of this a configuration file for Eclipse100 it maybe does not make totally sense to have the ecl100_versions top level node?

I agree, I just wanted a clear separation between the meta data and the versions. But yes, `ecl100_version` is probably not the best name for that section. Perhaps just `versions`?

> But - I guess it is when come all the way to the FORWARD_MODEL compatibility is most challenging.

I agree. My initial though on this was that we could make the argument handling of the `ecl` job a bit more explicit (utilizing `argparse`) and leave the version argument optional. You can then specify the version via the `--version` argument if you want, and if not, it will use the configured default version. I think this would be a good approach with respect to `simulation_job`. But also for the `forward model`-jobs, because then we can generate the old jobs and both support `ECLIPSE100_2012.1`, where the arglist would be generated as `--version 2012.1` and then the `ECLIPSE100` job where the `--version` will not be utilized.

You will then not be able to pass the the version explicitly to the `ECLIPSE100` forward model job, but besides that I think this would yield a good solution...

I am however very much open for suggestions on this!

**Comment by sondreso** [comment]
Part of https://github.com/equinor/ert/issues/833
