### ISSUE TITLE
Default location of site-config

### ISSUE THREAD

**Issue by andreabrambilla** [equinor/libres#671]
The location of the site-config file is specified at build time. It seems that this location is not the `install location` but the actual location of the file. 
If the value is not specified whan calling cmake (or in the cmake cache), by default it takes the path to the site-config in the source folder.
And that path is preserved as is, even after installing libres.
So, if someone relies on the default values, the installed version of libres refers to the site-config in the source folder instead of the installed site-config

* Definition of done
A user can use libres after having installed it and deleted the source folder

**Comment by jondequinor** [comment]
@sondreso maybe you can talk a bit about the state of this issue? I guess the underlying mechanisms haven't changed, but maybe become less painful?

**Comment by sondreso** [comment]
The default site configuration path still behaves as described above, however we are now (ab)using the SITE_CONFIG environment variable to construct the site config on startup rather than relying on the path specified by the user at compile time. The current setup satisfies the definition of done specified above, so I think we can close this issue!

**Comment by sondreso** [comment]
Or that is slightly incorrect: The new behavior comes from ERT. If you just install libres it will behave as described in the original issue.

**Comment by markusdregi** [comment]
ERT is no longer communicating the location of the site-configuration at installation time.
