### ISSUE TITLE
Tests creating files in the source folder

### ISSUE THREAD

**Issue by oyvindeide** [equinor/libres#813]
Several tests are creating files in the source folder, despite using `TestAreaContext`, which should put the test in a `tmpdir`, indicating that `TestAreaContext` has a bug. Decorating these functions with 
```
from tests.utils import tmpdir
@tmpdir()
```

puts the files in a `tmpdir` but doesn't fix the underlying problem. Tests in question:
- [x] test_ecl_config_creation from test_enkf_library
- [x] test_create from test_enkf_fs_manager1
- [x] test_rotate from test_enkf_fs_manager_2
- [x] test_with_gen_kw from test_enkf_runpath
- [x] test_without_gen_kw test_enkf_runpath
- [x] test_create2 from test_enkf_fs
- [x] test_transfer_var from test_enkf_transfer_env
- [x] test_simulation_model from test_enkf_sim_model
- [x] test_scale_obs from test_enkf_obs
- [x] testObs from test_enkf_obs
- [x] test_obs_block_scale_std from test_enkf_obs
- [x] test_load_results_manually from test_enkf_load_result_manually
- [x] test_config from test_enkf
- [x] test_run_context from test_enkf
- [x] test_run_context_from_external_folder from test_enkf

related to #742

**Comment by xjules** [comment]
`TestAreaContext` does not have a bug really, just that it's implemented over-complicatedly (and via C). The issue is partly caused by a new reference counter, which is basically implemented both in C and in (in-built) python too. The counters in C (ref to `EnkfFs`) are not decreased correctly and `enkf_fs_fsync(fs)` is still called after the tests end but the current folder is now your source folder and thus storage for those tests are placed there. Using `tmpdir` is wrapping the entire test function into another function and thus the scope (all fs parameters) are set to None. Therefore, the only viable solution at the moment is to use `tmpdir`. Still two new issues should be spawned: 1) Fix fs reference, relates not at the least to `enkf_fs_manager.__get_fs` and `enkf_fs_manager.dropOldestFileSystem` 2) Refactor `TestAreaContext` and `ErtTestContext`
