### ISSUE TITLE
Storage created on EnkFMain deletion

### ISSUE THREAD

**Issue by oyvindeide** [equinor/libres#855]
`storage` is often created when `EnkFMain` is deleted, this causes problems when `EnkFMain` is created multiple times in the same file location, often corrupting the existing `storage`. Problem became visible with: 9ca9544e3ab0e5141c4d0c3017c2c5f9bc410f64

**Comment by xjules** [comment]
when syncing via `enkf_fs_fsync(fs)` we should check whether the current `cwd` is the same as the one when `fs` was created

**Comment by pinkwah** [comment]
The `fsync` function can be safely removed entirely since there's no reason for it to exist. EnkfFs isn't a transactional database so all writes are partial anyhow. `block_fs_driver` only `fsync`s every 10 writes, for no apparent gain. If the power goes out your data is going to be corrupted anyway.

`fsync` only tells the OS to commit data from in-memory file cache to disk, which is unnecessary for us. It's enough that EnkfFs uses `fwrite` and does a `fclose` at the end. I don't see a reason why it should open every file at the start instead of on-demand either.
```c
fprintf(fh, "Hello, world!\n");
/* data is probably in C's FILE write-buffer */
fflush(fh);
/* data is committed to OS, but might not be on physical disks. Different
 * processes can access the same uncommitted (RAM-only) data
 * transparently. */
fsync(fileno(fh));
/* data is committed to disk by the OS. Might still not be 100% permanent on
 * disk because of disk-local cache */
```

**Comment by markusdregi** [comment]
This is no longer relevant
