### ISSUE TITLE
Bytes are not converted to string in external_ert_script.py

### ISSUE THREAD

**Issue by sondreso** [equinor/libres#863]
sys.stdout.write expects a string, while (in python3 only?) the stream from [Popen.communicate](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate) are open in byte mode by default. 

https://github.com/equinor/libres/blob/edbb1d58587c82acc5f87061baa0c6ae9eda6512/python/res/job_queue/external_ert_script.py#L14-L30

**Comment by sondreso** [comment]
Note: It's failing after the workflow has completed, so it doesn't actually influence the result. However it causes this error to be printed every time: 
`The script 'ExternalErtScript' caused an error while running:
write() argument must be str, not bytes`

**Comment by sondreso** [comment]
Can be replicated by running an external workflow in a python 3 environment

**Comment by pinkwah** [comment]
You can use the builtin library [`codecs`](https://docs.python.org/3/library/codecs.html) for converting to `str` safely.

```python
import codecs

[...]

self._stdoutdata = codecs.decode(self._stdoutdata, 'UTF-8', 'replace')
self._stderrdata = codecs.decode(self._stderrdata, 'UTF-8', 'replace')
```

This is preferable to `str(self._stdoutdata, 'UTF-8')` because it will not throw a `UnicodeDecodeError` if the output is not UTF-8, but rather try its best and replace all invalid codepoints with � (U+FFFD Replacement Character). This is controlled by the `'replace'` argument, with another reasonable option being `'ignore'`.

**Comment by sondreso** [comment]
It's also possible to open the streams in textmode by setting `encoding` in [Popen](https://docs.python.org/3/library/subprocess.html#subprocess.Popen).

**Comment by pinkwah** [comment]
That doesn't seem to be a thing in 2.7
