### ISSUE TITLE
Include decimals or remove .0 from status.json times

### ISSUE THREAD

**Issue by asnyv** [equinor/libres#903]
The status.json files are written with start and end times which always end with .0, this is misleading as it gives the impression of being to 1/10th second precision, while in reality it is rounded to nearest second. Should be fixed to either give an actual float, or to return an integer.

https://github.com/equinor/libres/blob/5a998e7f0d59c39b23739c7fdf9b27cac35c80f1/python/job_runner/reporting/file.py#L102

**Comment by markusdregi** [comment]
`0.0` is also a floating point number ;)

The accuracy of time is system dependent and you should not depend on this being with higher accuracy then one second. We could of course dump it as an integer, but that might cause problems for others. I suggest keeping it as...

**Comment by asnyv** [comment]
I agree that 0.0 is floating point, did not mean to give any other impressions ;) 

Just meant (as it looks like you understood) that to return a number which gives the impression of higher precision than what it is the reality in general is a bit risky, even though it looks fairly obvious when studying a status-file...

Can agree that there is always a risk of causing problems for others if you change.

**Comment by markusdregi** [comment]
> I agree that 0.0 is floating point, did not mean to give any other impressions ;)

It was a bad joke :)

I agree. Part of the problem is that there is no clear communication of what you can expect from these files. We are doing quite a bit of work, part by part on ERT. And when we get to the communication with the forward model, we will evaluate the status-files etc as well. I suggest that we keep your comment in mind for then. The goal should then be to have clarify documented specifications for what you can and cannot expect from these files ;)

**Comment by asnyv** [comment]
that's ok 👍

**Comment by markusdregi** [comment]
Thanks for the feedback by the way 👍
