### ISSUE TITLE
Support for SLURM queue system

### ISSUE THREAD

**Issue by joakim-hove** [equinor/libres#938]
In cooperation with TNO I am about to start implementing support for the slurm queue system in libres. My initial plan is to implement the slurm support along the lines of current lsf support - in particular the interaction with the slurm system will be by issuing shell commands and capturing and parsing stdout.

I create this issue here to give a heads up to the will be reviewers, and also invite invite early opinions on the implementation strategy. One question right away: Do you prefer one large PR or multiple small PR's? Personally I would prefer to submit multiple small PR's, but in that case the slurm implementation will not be usable before the last PR is merged.

**Comment by markusdregi** [comment]
Good evening Dr. Hove and welcome back to the ERT show 🎉 

As for the question I too prefer smaller PRs. The fact that the slurm implementation is not functional until the end is fine by me 🤷 Another option would be to create a feature branch for Slurm support, review smaller PR's into that one and in the end merge it into master. Do you have any preferences on this @sondreso?

As for keeping track of progress and getting an overview while reviewing; it would be nice if you could create a milestone or epic for slurm support and then you could try to write out a set of issues to highlight the initial plan for an approach and resolving them as you go along. Then we can add more issues as they come up.

Besides that, I can't think of anything else. Oh! Since Slurm is open source in contrast to for instance LSF; do you think it would be possible to write some integration tests that could run on Travis? Would at least be nice to investigate the feasibility of this...

**Comment by joakim-hove** [comment]
> Good evening Dr. Hove and welcome back to the ERT show 

Thank you!

> [...]  I too prefer smaller PRs.The fact that the slurm implementation is not functional until the end is fine by me

That is good - then I will head in that direction.

> it would be nice if you could create a milestone or epic for slurm support and then you could try to write out a set of issues to highlight the initial plan for an approach and resolving them as you go along. 

That is a good idea - I will do that.

> Since Slurm is open source in contrast to for instance LSF; do you think it would be possible to write some integration tests that could run on Travis? Would at least be nice to investigate the feasibility of this...

Whoha; might be possible - I will look into it. The thought of how to test has been goind as a background process for some time - maybe actually installing slurm and firing off proper tests is actually feasible - good idea!

**Comment by joakim-hove** [comment]
>  it would be nice if you could create a milestone or epic for slurm support

Unfortunately it seems I do not have the permission to create milestones :disappointed:

**Comment by markusdregi** [comment]
Created one ;)

**Comment by sondreso** [comment]
> As for the question I too prefer smaller PRs. The fact that the slurm implementation is not functional until the end is fine by me shrug Another option would be to create a feature branch for Slurm support, review smaller PR's into that one and in the end merge it into master. Do you have any preferences on this @sondreso?

A little late to the party here I see, but I also prefer the smaller PRs and don't mind the non functional driver while it's being worked on!
